[tox]
envlist = py310, py312, py313, lint

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/zat
deps =
    pytest
    coverage
    pytest-cov
commands =
    py.test --basetemp={envtmpdir} --cov=zat zat

[testenv:lint]
basepython = python3
deps =
    flake8
    black
    isort
commands =
    flake8 zat/ examples/
    black --check zat/ examples/ explorations/
    isort --check zat/ examples/ explorations/
